_core:
  default_config_hash: 5UHMfSmFu9rzzODqDc4xPCxSBK0u_u9xq0ftLz8uy4Q
iconset: social-icons--no-color
services:
  facebook: facebook
  whatsapp: whatsapp
  copy: copy
  twitter: 0
  facebook_messenger: 0
  email: 0
  pinterest: 0
  linkedin: 0
  digg: 0
  tumblr: 0
  reddit: 0
  evernote: 0
  print: 0
width: 30px
radius: '78% 62% 9% 91%/42% 39% 81% 18%'
print_css: ''
facebook_app_id: ''
node_field: 1
