login:
  authenticated:
    redirect_url: /
    weight: '-10'
  content_editor:
    redirect_url: /
    weight: '-10'
  administrator:
    redirect_url: /admin
    weight: '-10'
logout:
  authenticated:
    redirect_url: /user
    weight: '-10'
  content_editor:
    redirect_url: /user
    weight: '-10'
  administrator:
    redirect_url: /user
    weight: '-10'
