<?php

/**
 * @file
 * Primary module hooks for Views alias filter module.
 */

/**
 * Implements hook_views_data_alter().
 */
function views_alias_filter_views_data_alter(array &$data) {
  $data['node_field_data']['url_alias_filter'] = [
    'title' => t('URL alias filter'),
    'group' => t('Content'),
    'filter' => [
      'title' => t('URL alias filter'),
      'help' => t('Filtering nodes by URL aliases.'),
      'field' => 'nid',
      'id' => 'url_alias_filter',
    ],
  ];
}
