services:
  dpolac.twig_lambda.extension:
      class: DPolac\TwigLambda\LambdaExtension
      tags: [ { name: twig.extension } ]
parameters:
  cors.config:
      enabled: true
      # Specify allowed headers, like 'x-allowed-header'.
      allowedHeaders: ['x-csrf-token','authorization','content-type','accept','origin','x-requested-with', 'access-control-allow-origin','x-allowed-header','*']
      # Specify allowed request methods, specify ['*'] to allow all possible ones.
      allowedMethods: ['*']
      # Configure requests allowed from specific origins.
      allowedOrigins: ['http://localhost/','http://localhost:3000','http://localhost:3001','http://localhost:3002','http://patasdacasa.local.site','*']
      # Sets the Access-Control-Expose-Headers header.
      exposedHeaders: false
      # Sets the Access-Control-Max-Age header.
      maxAge: false
      # Sets the Access-Control-Allow-Credentials header.
      supportsCredentials: true
  twig.config:
    debug: true
    auto_reload: true
    cache: false